name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        mkdir project_build
        cd project_build
        cmake .. -B build
        cd build
        ctest
