name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir project_build
        cd project_build
        cmake .. -B build
        cmake --build build
    - name: Test
      run: |
        cd project_build
        cd build
        ctest
        
