name: C/C++ CI

on: [push,  pull_request]
 

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir project_build
        cd project_build
        cmake.exe -G "MinGW Makefiles" .. -B build
        cmake --build build
    - name: Test
      run: |
        cd project_build
        cd build
        ctest --output-on-failure
        tree
    - name: Generate Report
      run: |
        pip install gcovr
        gcovr project_build -r src --html --html-details -o coverage-html.html
        dir



        
