name: C/C++ CI

on: [push,  pull_request]
 

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir project_build
        cd project_build
        cmake.exe -G "MinGW Makefiles" .. -B build
        cmake --build build
    - name: Test
      run: |
        cd project_build
        cd build
        ctest --output-on-failure
    - name: Generate Report
      run: |
        pip install gcovr
        cd project_build
        mkdir coverage
        cd ..
        gcovr project_build -r src --html --html-details -o project_build/coverage/coverage-html.html
        cd project_build
        jar -cfM coverage.zip coverage
    - name: Archive Report
      uses: actions/upload-artifact@v2
      with:
          name: coverage
          path: project_build/coverage




        
